# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/pdx215/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter sm8350-common,$(TARGET_DEVICE)),)

endif
